### ISSUE TITLE
채널에 관한 소개

### ISSUE THREAD

**Issue by kciter** [Leop0ld/vuekr-bot#5]
9XD 슬렉에서는 누군가 가입했을때 채널에 대한 소개를 하더라구요 ㅎㅎ
뷰 슬렉도 사람이 많아짐에 따라서 채널 별 설명이 필요할 것 같습니다.
```
general
awesome
jobs
updates
question
news
```
우선은 이정도에 대해서 설명하면 좋을 것 같습니다.
혹시 작업해주시면 매우 감사드리지만 바쁘시다면 추후에 제가 작업해보겠습니다. :)

**Comment by Leop0ld** [comment]
아마 각 채널에 Bot이 추가되어 있다는 전제하에 channel을 구분하여 메세지를 다르게 보낼 수 있을 것으로 예상됩니다. 메인테이너가 바뀌었으므로 그 쪽에 다시는 것을 추천드립니다... ㅠㅠ 제가 유지를 잘 못하게 되어서 [gongzza 님 레포](https://github.com/gongzza/vuekr-bot) 로 넘기게 되었습니다.

**Comment by kciter** [comment]
아하 레포가 따로 있었군요 :) 감사합니다
